### ISSUE TITLE
Replace const supportedSensors in EUD-Services

### ISSUE THREAD

**Issue by martinste1n** [UniSiegenWiNeMe/opendash#1]
Wir sollten die folgende Zeile Code im EUD-Service 
```
const supportedSensors = {
  'od.sensor.powermeter': 'Energieverbrauch',
  'od.sensor.currenttemp': 'Temperatur',
  'od.sensor.currentbright': 'Helligkeit',
};
```

ersetzen durch eine ENV (gesetzt durch die jeweilige Instanz) Variable. Und statt einer Whitelist, sollte es eine Blacklist sein, die Standard Sensoren wie Switches, etc. rausschmeißt.

**Comment by zlls** [comment]
#
